### ISSUE TITLE
`ask_chatgpt` sessions

### ISSUE THREAD

**Issue by bschilder** [jcrodriguez1989/chatgpt#18]
> Ask ChatGPT: Opens an interactive chat session with ChatGPT

Does this means that a new session is opened every time the `ask_chatgpt` function is called, or is the same session used for each subsequent prompt?

If the former, then how does one start a new chatGPT session? Simply restarting the Rstudio session?

If the latter, how can we make the session persistent across queries?

Thanks, 
Brian

**Comment by jcrodriguez1989** [comment]
Hi @bschilder , 
yes, it "opens a new chat session" every time the `ask_chatgpt` function is called.
I mean, we are not opening sessions, just that {chatgpt} is not chatting with ChatGPT, it will send single unchained questions.
The goal of {chatgpt} is to provide help to R developers with tasks such as commenting, explaining, testing R code. Not to chat with ChatGPT.
If we couldn't find any use case in which a continuous chat with ChatGPT would help in these kinds of tasks.
May I know what is your use case here?

Thanks!

**Comment by bschilder** [comment]
Thanks for the clarification and the prompt reply @jcrodriguez1989 


I'm asking ChatGPT to produce severity score annotations (on a 1-4 scale) for a set of diseases and return a table with the scores for each of them in TSV format. However, we're doing this at scale for many thousands of diseases which would exceed the token limit, so I'm constructing queries as batches of 100 disease each. To ensure consistency of answers across batches, I would need to have a continuous session across `ask_chatgpt` calls.

From a formatting perspective, this would also help return the correct TSV format (it returns slightly different formats each time). Otherwise, it makes concatenated the results from each batch tricky.

**Comment by bschilder** [comment]
We're generating these annotations as part of a dataset to include within our R package:
https://github.com/neurogenomics/HPOExplorer

**Comment by jcrodriguez1989** [comment]
Oh, I get your idea.
So, this is not an R developer helper task.
It is mostly interfacing R to ChatGPT to programmatically ask questions.
I totally get your idea, and why it would be useful to have this feature implemented in {chatgpt}.
Thanks for your feedback, and we will be prioritizing this task for development.

**Comment by bschilder** [comment]
Yeah, it does go a bit beyond the R developer helper aspect of `chatgpt`, but I imagine this feature would open up quite a few avenues.

Thanks so much for being receptive to this idea!

**Comment by jcrodriguez1989** [comment]
Hi @bschilder , I've been working on this.
The ChatGPT API allows having a conversation, however, it requires that we send all of the conversation on each API query.
Thus, it is possible that if your text is too long, `{httr}` will fail. This is just a hypothesis, so I would be glad if you can test this work-in-progress version.
Please install this new version with:

```r
remotes::install_github("jcrodriguez1989/chatgpt", ref = "feature.jcr.conversation_with_chatgpt")
```

As an easy test example, I did this:
```r
chatgpt::reset_chat_session("You are a helpful math assistant")
chatgpt::ask_chatgpt("2 + 100")
chatgpt::ask_chatgpt("And what is the square of that?")
chatgpt::ask_chatgpt("And what is the square of that?")
```

**Comment by nickhalden159** [comment]
@jcrodriguez1989, thanks! Not the original commenter, but I was having the same issue, and the your last post works perfectly!

**Comment by bschilder** [comment]
Amazing, thanks for the lightning-fast turnaround @jcrodriguez1989 ! I'll give this a try and let you know what I find.

**Comment by bschilder** [comment]
Ok, and pretty quickly ran into issues with total token length. In this short example, it mostly stems from the completion outputs being so long. This might have to do with how I'm asking it to format the results (as a TSV). I'll see if I can engineer the prompt a bit better to help with this.

That said, even if I get it to shorten the outputs, I'll likely still run into the issue of resubmitting the full convo even time (as you mentioned before). So having a way to get around this latter issue will become quite important for submitting 1000s of disease terms.

## Reprex

### Code

```R
#### Set up role ####
system_role="You are an expert biomedical scientist."
chatgpt::reset_chat_session(system_role = system_role)

#### Set up scale ####
prompt <- "Create a disease severity score on a scale using the following scale: \"Mild\": (Severity_score=4), \"Borderline\": (Severity_score=3), \"Severe\": (Severity_score=2), \"Profound\": (Severity_score=1)\nWhen asked, you will use these criteria to assign disease terms a severity score, output in tab-separate values (.tsv) format with 4 columns: 'disease_name','disease_id','severity_score_numeric','severity_score_name'."
chatgpt::ask_chatgpt(question = prompt)

#### Annotate terms ####
question <-  "Annotate the following disease terms using the aforementioned severity_score: \n- Developmental and epileptic encephalopathy 96 (ID: OMIM:619340)\n- Pseudohyperkalemia, familial, 2, due to red cell leak (ID: OMIM:609153)\n- Dystonia with ringbinden (ID: OMIM:224550)\n- Immunoglobulin kappa light chain deficiency (ID: OMIM:614102)\n- White-Kernohan syndrome (ID: OMIM:619426)"
chatgpt::ask_chatgpt(question = question)
```

### Error
```R
Error in gpt_get_completions(question, messages = chat_session_messages) :
list(message = "This model's maximum context length is 4097 tokens. However, you requested 4437 tokens (341 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.", type = "invalid_request_error", param = "messages", code = "context_length_exceeded")
```

## Checking tokens

Just checking the number of tokens in total. 
This probably isn't the exact same way that chatGPT counts tokens, but does seem odd that it's >3x my estimate here. I'll have to look into how chatGPT does this to try and align it better.

Of course, I'm also not accounting for the output length, which is the majority of it.
```R
tokens <- tokenizers::tokenize_words(paste(system_role, prompt, question,sep=" "))
length(tokens[[1]])
```
```
106
```

## Additional notes

- After running an initial set of queries, sometimes when I try to reset the session with `chatgpt::reset_chat_session` and then ask it a new question, R freezes up when I run `chatgpt::ask_chatgpt` (i.e. it just runs indefinitely). Though it's not consistent. If I can figure out how to replicate it, I'll submit a separate issue documenting it.

Thanks again for all your help!, 
Brian

## Session info
<details>
```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gptPhD_0.99.0

loaded via a namespace (and not attached):
 [1] bitops_1.0-7         fs_1.6.1             usethis_2.1.6        devtools_2.4.5      
 [5] httr_1.4.5           rprojroot_2.0.3      SnowballC_0.7.0      tools_4.2.1         
 [9] profvis_0.3.7        utf8_1.2.3           R6_2.5.1             lazyeval_0.2.2      
[13] BiocGenerics_0.44.0  colorspace_2.1-0     urlchecker_1.0.1     tidyselect_1.2.0    
[17] prettyunits_1.1.1    processx_3.8.0       curl_5.0.0           ontologyIndex_2.10  
[21] compiler_4.2.1       graph_1.76.0         cli_3.6.0            Biobase_2.58.0      
[25] BiocCheck_1.34.3     network_1.18.1       plotly_4.10.1        chatgpt_0.2.2       
[29] scales_1.2.1         callr_3.7.3          RBGL_1.74.0          stringr_1.5.0       
[33] digest_0.6.31        rmarkdown_2.20.1     stringdist_0.9.10    pkgconfig_2.0.3     
[37] htmltools_0.5.4      sessioninfo_1.2.2    fastmap_1.1.1        htmlwidgets_1.6.1   
[41] rlang_1.1.0          rstudioapi_0.14      shiny_1.7.4          generics_0.1.3      
[45] jsonlite_1.8.4       statnet.common_4.8.0 tokenizers_0.3.0     dplyr_1.1.0         
[49] RCurl_1.98-1.10      magrittr_2.0.3       ggnetwork_0.5.12     Rcpp_1.0.10         
[53] munsell_0.5.0        fansi_1.0.4          lifecycle_1.0.3      stringi_1.7.12      
[57] yaml_2.3.7           pkgbuild_1.4.0       biocViews_1.66.3     grid_4.2.1          
[61] parallel_4.2.1       promises_1.2.0.1     crayon_1.5.2         miniUI_0.1.1.1      
[65] lattice_0.20-45      knitr_1.42           ps_1.7.2             pillar_1.8.1        
[69] RUnit_0.4.32         codetools_0.2-19     stats4_4.2.1         pkgload_1.3.2       
[73] XML_3.99-0.13        glue_1.6.2           evaluate_0.20        data.table_1.14.8   
[77] remotes_2.4.2        BiocManager_1.30.20  vctrs_0.6.0          httpuv_1.6.9        
[81] gtable_0.3.1         purrr_1.0.1          tidyr_1.3.0          HPOExplorer_0.99.6  
[85] cachem_1.0.7         ggplot2_3.4.1        xfun_0.37            mime_0.12           
[89] xtable_1.8-4         devoptera_0.99.0     coda_0.19-4          later_1.3.0         
[93] viridisLite_0.4.1    tibble_3.2.0         memoise_2.0.1        ellipsis_0.3.2      
[97] here_1.0.1 
```
</details>

**Comment by shaynweidner** [comment]
Just my $.02, but this is a common problem but I don't know if anyone has created a solution in R.  Python has a package called langchain that is supposed to address this, but I haven't had the opportunity to test it.  Among other things, it's supposed to condense/summarize older messages in an extended chat session while letting the more recent messages remain.  

A clunky solution would be to keep a running tab of how many tokens were used for each pair of sent/received messages, along with an assumption of how many tokens the response will be, send a separate call to openai to summarize the older messages to free up some token capacity, somehow append that summary to the system prompt, and then send the modified chat history to openAI.  I'm sure there's a more elegant approach from someone more clever than me.

However, in this use case, if a single response from openAI is giving such a large response then I'm not sure how to go around that other than requesting fewer annotations at a time.  If you have beta access to it or are willing to wait, gpt4's increased token limit (and increased cost) may be a good enough "solution".  When you use chatGPT proper you can sometimes get by with typing "continue", so there could be an option there, too, but you'd have to figure out how to get openAI to send you an incomplete response.

I don't have the capacity to work on any of this right now, but one way to incorporate Juan's changes would be to default the Chat shiny app to always persist the chat history, and add an additional button to the shiny app that allows you to reset the chat history.

**Comment by jcrodriguez1989** [comment]
I am closing this issue, as the original topic (chat sessions) got solved, tested, and is currently released.
For the next faced issue, I see this is an OpenAI issue. Right now, the token limit is really low even for trivial tasks. I think the best we can do for now is using larger models (as gpt-4), or some sort of prompt engineering as @shaynweidner suggested (great summarization you gave btw!).

Thanks everyone for pointing these out.
And hoping that OpenAI improves how they handle/manage sessions, instead of sending all of the session on each query.
