### ISSUE TITLE
clipr for using the code copied to the clipboard

### ISSUE THREAD

**Issue by denisabd** [jcrodriguez1989/chatgpt#19]
Hello there - great package, I just thought about building something like this, but it is already done 👍  

I think a good addition could be using the function code that is copied to the clipboard, similar to `reprex` package. User will select the code, Ctrl/Command + C and run any of the package functions. 

It will require `clipr` as a dependency and one more enviroment variable that will use this "new" approach by default. 
Alternatively we can allow running functions without specified value for `code`  argument and it will use the code from clipboard and `stop()` when the clipboard is NULL.

I just tried it and works quite well.

I can work on it and raise a PR if you're interested. Please let me know your thoughts.

Have a great day!

Denis

**Comment by denisabd** [comment]
I actually went ahead and created a [fork](https://github.com/denisabd/chatgpt) 
Check it out and let me know if I can raise a PR for it

Thanks in advance!

**Comment by jcrodriguez1989** [comment]
Hi @denisabd , thanks for proposing this idea!
Just to be clear, this use-case will only be applied when running the function through the terminal. Right now, if we use the addins without selecting code, it will use all of the current file's code.
But, yes, I love it. Could you create the PR, I have some comments for the code.
First of all, could you replace `str_replace_all(code, "\"", "'")` by `gsub('"', "'", code)`? So we avoid importing `{string}`.
Thanks!

**Comment by jcrodriguez1989** [comment]
What about if instead of this kind of code:
```r
comment_code <- function(code = NULL) {

  if (is.null(code)) {
    code <- read_clip(allow_non_interactive = TRUE)
  }

  if (is.null(code)) {
    stop("Add your code as an argument of copy code to clipboard")
  } else {
    code <- paste(str_replace_all(code, "\"", "'"), collapse = "\n")
  }

  prompt <- paste0('Add inline comments to the following R code: "', code, '"')
  parse_response(gpt_get_completions(prompt))
}
```

we do (to keep it as simple as possible):
```r
comment_code <- function(code = clipr::read_clip(allow_non_interactive = TRUE)) {
  prompt <- paste0('Add inline comments to the following R code: "', code, '"')
  parse_response(gpt_get_completions(prompt))
}
```

**Comment by denisabd** [comment]
Will do in the next or two. Do I raise a PR to `develop` branch?

**Comment by jcrodriguez1989** [comment]
Yes, please.
thanks!

**Comment by jcrodriguez1989** [comment]
Fixed by https://github.com/jcrodriguez1989/chatgpt/pull/21
@denisabd , thanks for your contribution!!
