### ISSUE TITLE
Export API code as new package

### ISSUE THREAD

**Issue by sebastian-c** [jcrodriguez1989/chatgpt#2]
Hi,

I was looking for an R package to make the API calls to chatGPT and I came across your package. You package does two things:
- Pulls data from chatGPT
- Formats requests so chat GPT can understand them

Would it be possible to separate the first into its own package? I think a lot of R users would be interested in it.

**Comment by jcrodriguez1989** [comment]
Hi @sebastian-c , what do you mean?
Would you like a package with a function like `ask_chatgpt(message)`, that returns ChatGPT's reply to the `message`?
If so, I could export `gpt_get_completions` function. Meanwhile, you can test it with `chatgpt:::gpt_get_completions("What do you think about R language?")`.

**Comment by jcrodriguez1989** [comment]
Closed due to inactivity, I think [this](https://github.com/jcrodriguez1989/chatgpt/pull/4) closes what @sebastian-c asked for.
If not, let me know.
Thanks!

**Comment by sebastian-c** [comment]
Yep, exactly, thanks!
