### ISSUE TITLE
gpt-4 support is still missing.

### ISSUE THREAD

**Issue by tolgakurtuluss** [jcrodriguez1989/chatgpt#25]
Hey,

Seems like gpt-4 models listed below are still not covered.

All models;
[OpenAI models page](https://platform.openai.com/docs/models/gpt-4)

Error that occured when tried "gpt-4" for Sys.setenv(OPENAI_MODEL = "gpt-4")
```
Error in gpt_get_completions(question) : 
  list(message = "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?", type = "invalid_request_error", param = "model", code = NULL)
```

**Comment by jcrodriguez1989** [comment]
Hi @tolgakurtuluss , GPT-4 support is still under development.
You can test its functionality by installing its dev branch with:
`remotes::install_github("jcrodriguez1989/chatgpt", ref = "feature.jcr.conversation_with_chatgpt")`

**Comment by tolgakurtuluss** [comment]
Maybe it's because I installed package via CRAN. I'll give it a try with dev branch. Thanks!
