### ISSUE TITLE
Could you please show how to change the model from gpt 3.5 to gpt 4?

### ISSUE THREAD

**Issue by RanTongUTD** [jcrodriguez1989/chatgpt#30]
Could you please show how to change the model from gpt 3.5 to gpt 4 by changing the settings? Thank you

**Comment by jcrodriguez1989** [comment]
Just set the `OPENAI_MODEL` environment variable with the gpt 4 model name:
```r
Sys.setenv(OPENAI_MODEL = "gpt-4")
cat(ask_chatgpt("What do you think about R language?"))
```

**Comment by RanTongUTD** [comment]
Thank you for your reply!  But I notice the following problem while trying to play with the settings, even though I have a member ship:
Sys.setenv(OPENAI_MODEL = "gpt-4")
> cat(ask_chatgpt("What do you think about R language?"))
Error in gpt_get_completions(question) : 
  list(message = "The model: `gpt-4` does not exist", type = "invalid_request_error", param = NULL, code = "model_not_found")

**Comment by jcrodriguez1989** [comment]
This is more of a question to OpenAI. So far, I guess your account hasn't been granted GPT-4 API access.
Check out this thread https://community.openai.com/t/when-i-try-the-gpt-4-model-chat-completion-in-api-request-i-get-an-error-that-model-does-not-exist/98850 .
