### ISSUE TITLE
Error: exceeded the current quota

### ISSUE THREAD

**Issue by ManuelSpinola** [jcrodriguez1989/chatgpt#32]
When I use chatgpt I recieve an error:

Warning: Error in gpt_get_completions: list(message = "You exceeded your current quota, please check your plan and billing details.", type = "insufficient_quota", param = NULL, code = NULL)

However if I sign in in OpenaAI I can use it without any problem.

**Comment by jcrodriguez1989** [comment]
Hi @ManuelSpinola , this is not a `{chatgpt}` R package issue.
This is related to your OpenAI billing, by Googling I found this FAQ from OpenAI https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details
It is expecting that you set a payment method.

Best!
