### ISSUE TITLE
Returns character(0) when querying too quickly (e.g. in a loop)

### ISSUE THREAD

**Issue by dohdoubleg** [jcrodriguez1989/chatgpt#33]
When calling `ask_chatgpt` in a `for` loop, I get maybe 3 returns with answers, but after that it will return "character(0)" which just seems to be a null character object. When this occurs in the loop, it stops operation with an error about "...replacement has length 0."

I used this workaround, which was effective for my use:  insert `sys.sleep(x)` into the loop, where x is a number of seconds to temporarily suspend operation. 5 wasn't enough and 15 worked, but it appears as if more complex queries and/or higher numbers of loop iterations requires higher times; I had to move to 20 to get a loop to run 121 times.

I'm not sure what's causing the null response and this workaround suits me fine, but would be interested to learn why it occurs in case faster loops are possible.

**Comment by jcrodriguez1989** [comment]
Hi @dohdoubleg , thanks for finding and submitting this issue.

Unfortunately, I am not being able to reproduce your bug. Would you provide me with a reproducible example? Probably my testing example is too simple for ChatGPT to solve (`gpt_replies <- lapply(1:10, function(i) chatgpt::ask_chatgpt(paste0(i, " ** ", i)))`.
Also, which version of the package are you using?
Thanks!

**Comment by tcash21** [comment]
I'm getting `character(0)` on my first query as well, without looping. I tried re-installing the latest from Github but no luck.

**Comment by tcash21** [comment]
Once I upgraded to the dev branch I got an error message about billing. Added a credit card and used a new secret key but still getting this message. Any ideas?
```
Error in gpt_get_completions(question, messages = chat_session_messages) : 
  list(message = "You exceeded your current quota, please check your plan and billing details.", type = "insufficient_quota", param = NULL, code = NULL)
```

**Comment by dohdoubleg** [comment]
> Hi @dohdoubleg , thanks for finding and submitting this issue.
> 
> Unfortunately, I am not being able to reproduce your bug. Would you provide me with a reproducible example? Probably my testing example is too simple for ChatGPT to solve (`gpt_replies <- lapply(1:10, function(i) chatgpt::ask_chatgpt(paste0(i, " ** ", i)))`. Also, which version of the package are you using? Thanks!

Thank you. I believe this may have been an error on my side. Early on, I was using code from RBloggers to run CGPT: https://www.r-bloggers.com/2023/03/call-chatgpt-or-really-any-other-api-from-r/

That defines a function ask_chatgpt. I later installed and thought I was using your package, but I think I was actually calling that first function. I was also using my free credits, and now I'm on a paid account.

In any case, your code works nicely and I no longer get that error when testing. If something occurs during longer loops, I'll update, but I think this can be closed. Thank you!
