### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by esimms999** [jcrodriguez1989/chatgpt#34]
"The following environment variables variables can be set ..." - the word "variables" is repeated.

**Comment by jcrodriguez1989** [comment]
Thanks for this finding!!
If you have some time, could you create a PR to fix it? Just changing the README.Rmd file. Thanks!

**Comment by esimms999** [comment]
I do not have permission to create a branch.
Have you given any presentations on this package? Are there any recordings available?
--- Eric Simms



    On Thursday, April 27, 2023 at 03:06:09 PM EDT, Juan C Rodriguez ***@***.***> wrote:  
 
 


Thanks for this finding!!
If you have some time, could you create a PR to fix it? Just changing the README.Rmd file. Thanks!

**Comment by jcrodriguez1989** [comment]
Oh, no, only I have permission to create branches for this repo. To create PR for my repo, you should:
1. fork this repo.
2. create a branch on your forked repo.
3. submit a PR from your branch to my repo.

Here it is greatly explained how to contribute to open source https://github.com/firstcontributions/first-contributions 🎉

I haven't done any presentations or recordings for this package yet 😅

**Comment by jcrodriguez1989** [comment]
Fixed by https://github.com/jcrodriguez1989/chatgpt/pull/35

**Comment by jcrodriguez1989** [comment]
@esimms999 , about the R in pharma conference, I am not sure how my chatgpt work would fit in there.
I know chatgpt would be really beneficial -if responsibly used- for pharma, but not sure how my work directly impacts there. I guess, it is a broader work what I've done here.
