### ISSUE TITLE
Error: "`OPENAI_API_KEY` not provided."

### ISSUE THREAD

**Issue by Beliavsky** [jcrodriguez1989/chatgpt#41]
In Rgui on Windows, I get

> ask_chatgpt("How many hours are there in a day?")
Error in gpt_get_completions(question, messages = chat_session_messages) : 
  `OPENAI_API_KEY` not provided.

How do I provide OPENAI_API_KEY?

**Comment by jcrodriguez1989** [comment]
Hi @Beliavsky ,
it is explained in the README, you can check it out here https://github.com/jcrodriguez1989/chatgpt#requirements
TL;DR, once you have your OpenAI API key, you do `Sys.setenv(OPENAI_API_KEY = "sk-...")` before running any chatgpt function.
