### ISSUE TITLE
Is there a way to get metadata of responses? 

### ISSUE THREAD

**Issue by dohdoubleg** [jcrodriguez1989/chatgpt#43]
I have my model set, but I want to be able to have confirmation attached to output about which model was used to generate the response. ChatGPT suggests this is possible using Python, where "metadata" is another option that can be set along with temperature, max tokens, etc. Below is the Python code it suggested to me; I looked through the repository and didn't see a metadata option.

Use case: My account provider is telling me I should have access to GPT-4. After generating an API key under the proper default organization, and attempting to set GPT-4 in R, I get the error suggesting I don't have access to it. In the Rate Limits and Playground, I also don't see evidence of having access to GPT-4, only GPT-3.5-turbo. That's fine, that appears to be an administrative error. 

But then when having 3.5-turbo set in R, and I ask_chatgpt which model it is, it tells me it is "a simple GPT-2 model." On the other hand, when using the chat.openai.com, it gives me a dramatically different answers about which model it is. Asking for this information probably isn't a reliable solution. So while the OPENAI_MODEL should be the straightforward validation of which model is generating the response, I'm hoping for another way of confirming.

___________________________________________
import openai
openai.api_key = "YOUR_API_KEY"

prompt = "Some text you want to generate a response for"
model = "text-davinci-002"  # Replace with the CHTAGPT model ID
temperature = 0.5
max_tokens = 50
metadata = True  # Include metadata in the response

response = openai.Completion.create(
    engine=model,
    prompt=prompt,
    temperature=temperature,
    max_tokens=max_tokens,
    metadata=metadata
)

print(response.choices[0].text)  # Print the generated text
print(response.choices[0].metadata)  # Print the metadata

**Comment by jcrodriguez1989** [comment]
Please, install this branch `remotes::install_github("jcrodriguez1989/chatgpt@feature.jcr.new_verbosity_level")`.
And try doing:
```r
Sys.setenv(OPENAI_VERBOSE = 2)
cat(ask_chatgpt("What do you think about R language?"))
```

**Comment by dohdoubleg** [comment]
Thanks for that, installed and tried, got: 

> Sys.setenv(OPENAI_VERBOSE = 2)
> cat(ask_chatgpt("What do you think about R language?"))

Error in if (as.logical(Sys.getenv("OPENAI_VERBOSE", TRUE))) { : 
  missing value where TRUE/FALSE needed

**Comment by jcrodriguez1989** [comment]
Have you restarted your R session after reinstalling?

**Comment by dohdoubleg** [comment]
That worked, thank you. :clap::clap::clap::rocket:
