### ISSUE TITLE
Specify to use v4.0 model?

### ISSUE THREAD

**Issue by jcwhitmer** [jcrodriguez1989/chatgpt#45]
Any chance that we can pass an argument to specify the model to use for the queries made through this package? Appreciate you putting it together and prevent meaningless JSON writing.

**Comment by jcrodriguez1989** [comment]
Hi @jcwhitmer , 
This is explained in [in the README](https://github.com/jcrodriguez1989/chatgpt#use-chatgpt-behind-a-proxy). The `OPENAI_MODEL` environment variable.
Or am I getting wrong your question?
