### ISSUE TITLE
"You exceeded your current quota.." Except I have not?

### ISSUE THREAD

**Issue by tomasrei** [jcrodriguez1989/chatgpt#46]
Hi, maybe I missed something, but this package should work with a free plan on chatgpt? I am able to ask questions on the chatgpt webpage but in Rstudio I get the message:

````
Error in gpt_get_completions(question, messages = chat_session_messages) : 
  list(message = "You exceeded your current quota, please check your plan and billing details.", type = "insufficient_quota", param = NULL, code = NULL)
````

when I run 
````
cat(ask_chatgpt("What is you purpose?"))
````

Maybe it only works with a payed subscription?

Thanks,
Tom

**Comment by jcrodriguez1989** [comment]
Yes, you need to set a billing method at least.
