### ISSUE TITLE
Can not switch to gpt-4

### ISSUE THREAD

**Issue by bidcrt** [jcrodriguez1989/chatgpt#56]
Greeting,
I have tried to use usethis::edit_r_environ() and add OPENAI_MODEL="gpt-4," but it does not work for me to switch to gpt-4. Am I right on that?
Thanks.
RStudio-2023.12.1-402
R-4.3.3 for Windows

**Comment by jcrodriguez1989** [comment]
Hi @bidcrt , I am not sure how setting env vars is managed by `usethis`.
To change the used model I would simply put this at the very first of my scripts: `Sys.setenv(OPENAI_MODEL = "gpt-4")`. 
Or I would add `OPENAI_MODEL="gpt-4"` at my `~/.Renviron` file.

To test that the env var is correctly set, you can try if it errors on non existing models:
```r
 Sys.setenv(OPENAI_MODEL = "FAKE_MODEL")
> chatgpt::ask_chatgpt("In 4 words describe the R language.")
Error in gpt_get_completions(question, messages = chat_session_messages) :
list(message = "The model `FAKE_MODEL` does not exist or you do not have access to it.", type = "invalid_request_error", param = NULL, code = "model_not_found")
> Sys.setenv(OPENAI_MODEL = "gpt-4")
> chatgpt::ask_chatgpt("In 4 words describe the R language.")
[1] "Statistical computing and graphics software."
```

**Comment by bidcrt** [comment]
Hi, @jcrodriguez1989, thanks for your reply. I have tried,  but when I asked GPT, it said, "As an AI, I'm currently based on OpenAI's GPT-3 model. There's no GPT-4 model available as of now." 
![326](https://github.com/jcrodriguez1989/chatgpt/assets/149823554/710dd346-224b-464f-8159-06adc24d3852)

**Comment by bidcrt** [comment]
My bad I checked the Usage it said I had used gpt-4 XD.
